### ISSUE TITLE
GPL-383-1 - Consumer issue

### ISSUE THREAD

**Issue by pjvv** [sanger/General-Backlog-Items#20]

**Comment by emrojo** [comment]
Relates to RT 687721
Over the last few weeks (end of March.. beginning April) we have been getting requests (PAM,CASM,SAM) to add missing accession numbers to mlwh + warehouse2 which are present in SS
This just involves touching the samples and the accessions are populated. 
There are deadletter error messages>> 

The consumers that convert the lightweight message to big one seems to be losing connection to rabbitmq in their localhost. When they lose connection seems they stop working until restarted… It has been happening at least from 2019-10-03T16:36. 

Receiving errors like this: 
[2019-10-03T16:36:03.950354 #28642] ERROR -- : Bad file descriptor (Errno::EBADF)

**Comment by emrojo** [comment]
Turn out that consumer loses connection because of deployment (during the time the services is restarted). Service stop/start doesn't perform it in a clean way and consumers start logging errors continuously until they stop. 
From ticket, samples are accessioned but the message is not in the warehouses, so it has to be either:
* Stored in the deadletter/unrouted queue
* Lost because of killing the process while processing a message during deployment

Note: accessioning job does seem to stop retrying on accessioning samples when this happens after 3 failing days.  The condition of failing accession could be because the answer from accessioning service does not include the accession number, which it could be a normal behaviour.

**Comment by emrojo** [comment]
More info from @JamesGlover about the problem:
1. There is something odd going on with logging, we’re seeing log messages get lost which MUST have been logged. (ie. later messages in the same method are logged, and earlier messages are missing, despite there being no branching in the method) This may or may not be related
2. As far as RabbitMQ is concerned, the consumers remain connected, they just stop pulling messages (their buffers fill up to the maximum size)
Its connected to dead-lettering. Dead lettering does work, but it appears that every time it happens their is a chance things will stall.
3. As best I can tell, is we’re not stalling somewhere in our code. It appears that the consumer finishes processing the message, but just stops picking up new ones.
4. I’d shelved the story until we were onto the new infrastructure, to rule out issues with the old kernel and to allow us to fully update ruby etc.

**Comment by emrojo** [comment]
The main cause of the warehouse problem was a crash of Rabbitmq server because server ran out of memory.
Causes found:
 * Memory leak on QcReportJob - already known bug; memory is not liberated until the leaking delayed job is restarted. This is the main cause of this problem.
 * Consumer logs are too busy/verbose on deployments, and that creates memory problem: NoMemoryError and logging problems (some messages get lost). This could be affecting as well.
 * Dead letters for lightweight messages are not being queued. This is low priority.

**Comment by emrojo** [comment]
Assumption: After rabbitmq crash, consumers detect an exception while running a sql query, so they try to restart from beginning by unsubscribe and try to subscribe again. This new connection attempt seems to reuse the exchange from the old connection, that after rabbitmq restart is not valid anymore. I'll try to replicate in local.

**Comment by emrojo** [comment]
In local consumers recovered connection with rabbitmq and with mysql. Found that the first message after a mysql connection error is always lost (goes directly to deadletters), while the following messages are requeued. Added a pull request to solve this.
Main problem could be due to the way rabbitmq process died (crashing). I tried to replicate with kill -9 but didnt work the same way and maybe it won't happen the same way next time.

Issues to solve:
* Logging in consumers is too verbose
* Memory leak QcReportJob
* When Rabbitmq crash because of memory full this will happen again. A temporal solution while we find the leak could be to restart delayed jobs when memory has reach a defined limit of 85-90%.

**Comment by emrojo** [comment]
The action that performs the OS to free memory when memory gets full (OOM killer) doesn't seem to be configured on a specific percentage of memory occupation. We could try to change to 3% allocation for root, or safer option could be to perform this restart with monit instead of delegating to the OS which it seems it should be the last resource.

**Comment by emrojo** [comment]
These are the workarounds for the moment:
* Merge request 75 in psd-deployment: consumers and delayed jobs will be restarted every night to free any memory lost by leaks during the day.
* Minor fix: first message after database connection error was not requeued (like subsequente messages) but directly sent to deadletters. Now is requeued as well.
https://github.com/sanger/sequencescape/pull/2619

In order to progress in the solution the following steps are proposed:
1. Instead of restarting the suspicious processes every night, perform it only if there is a leak detected. That could be approached by measuring memory increases between memory resources in the process by using monit, for example.
2. Find the memory leak, potentially is happening inside QcReportJob
