### ISSUE TITLE
DPL-512 Bioscan OKR: Export of library pooled samples tube to Traction

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#220]
**Description**
The end point of Bioscan library prep is a tube containing up to 9216 samples that needs to be exported into the Traction LIMS for PacBio sequencing. This story is about better defining how that export should be built, and how to build it in a generic way that makes it useful for other projects and LIMS that also need to export library pools to Traction.

**Who the primary contacts are for this work**
Scott T
Emma B
PSD

**Knowledge or Stake holders**
Steve I (Traction)
Eduardo MJ and Stuart M (RabbitMQ and Red Panda)

**Additional context or information**
What are the common elements here with other projects in PSD development? 
Can we define a clear generic way to do this tube export? 
Do we need stories in the Bioscan OKR to build this export process? 
Do we need distinct Sequencescape and Traction consumers written in Python to take advantage of the common python library that Eduardo has developed for RabbitMQ and Red Panda schema interactions?

**Comment by andrewsparkes** [comment]
For MVP is there a sequencescape import now in traction that works? Will we want 9216 samples or just 1 (e.g. a compound sample).

**Comment by stevieing** [comment]
Initial thoughts:

- We will only need to import a compound sample. Long Read do not need to know about the 9216 samples
- We will need to import it as a library. Do we need to change the structure or would it be better to create a request and sample?
- The barcode will need to be human readable and preferably 2D.
- It would be much better to use the message queues rather than import via Sequencescape as we are trying to remove the dependency. that way we can generate a standard schema for importing libraries which could be reused.
- We can modify the traction reception API to cope with libraries. What extra information will we need?
- My initial estimations that there will be 2-3 stories for this piece of work.

**Comment by stevieing** [comment]
Tasks to complete:
- [ ] create a message schema for the library import
- [ ] process diagram for the import through to run creation and download of the mBrave file
- [ ] story for importing libraries into traction.
- [ ] Clarify what information is needed for the run. The sample sheets are different for tagged and untagged samples so I am not quite sure how it will work for Bioscan.
