### ISSUE TITLE
DPL-535 As PSD we would like the SequenceScape integration test suite to run every night so that we get faster feedback on breaking changes.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#225]
**Describe the Housekeeping**
As PSD we would like the SequenceScape integration test suite to run every night so that we get faster feedback on breaking changes.

**Additional context**
This is to mitigate the difficulty in knowing what features in SequenceScape are impacted by any particular change. (Especially in areas using metaprogramming)

**Acceptance criteria**

- [x] Integration Test Suite runs every night on develop?
- [x] PSD are alerted to any failure in the morning. (Maybe a regular check at standup?)

**Comment by emrojo** [comment]
Features added:
- Run the pipeline every night with uat
- Write the result in the #exceptions-uat-training slack channel
- Split all tests in 2 groups of tests using knapsack pro

Future improvements:
- Logs do not display colours as when we run them in local. This seems to be related with the way they are displayed in the gitlab runner.
- Knapsack jobs are not running in parallel. If we want to improve the time it takes to run, we should check why the jobs are not loaded by the 2 current runners available. This would reduce the running time from 40 minutes to 20 minutes (which potentially could be reduced further by increasing the number of runners in gitlab)

**Comment by emrojo** [comment]
Just checked, the problem with the jobs in parallel was because in the gitlab runners servers that we keep in openstack in psd-tools, the file  ```/etc/gitlab-runner/config.toml``` had the value ```concurrent``` set to 1. We have changed to 2 and restarted the runners so now it run jobs in 2 runners in parallel.

**Comment by emrojo** [comment]
Run out of space in disk yesterday, so i've done a modification to run all runners using the same image generated by docker, instead of each one downloading and configuring themselves.
Some advantages on this:
- We only need to maintain the Dockerfile to support any new changes for running the tests
- The docker image is build when we modify the Dockerfile, but if we don't change it, the jobs will use the latest generated docker image to run the tests.
- All 4 jobs will use the same docker image to run the tests. The docker image can also be downloaded in local to run the tests.

**Comment by emrojo** [comment]
New merge request: psd/integration-suite/-/merge_requests/68

**Comment by emrojo** [comment]
It seems the issue is more common than we expected:

https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27332

Finally had to solve it using a crontab that will run every 5 mins. We might move everything to github in any case so it is not be very important to solve it in a better way.
