### ISSUE TITLE
DPL-799 As a Team Lead (TW) I would like to determine what limitations there are if any on Tecan machine cherry picking due to plate purposes so that we understand the options for RVI.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#308]
**Description**
As a Team Lead (TW) I would like to determine what limitations there are if any on Tecan macine cherry picking due to plate purposes so that we understand the options for RVI.

**Who the primary contacts are for this work**
TW 

**Knowledge or Stake holders**
EMR AS 

**Additional context or information**
To support the RVI projects aspirations we need to be able to cherry pick from source plates to destination plates (shallow 96 well plates) in the following scenarios:

- From source well plates with that have been stamped from deep well plates that have a fixed plate purpose of LSW-96 Stock
- To destination plates whose samples are destined for one RVI pipeline 
- To destination plates which may be cherry picked from again, e.g. act as a source plate

Assuming this operation will be supported by Limber and therefore the plates need a single plate purpose - what options have to make the above work?

Is there an option of not using Limber / SequenceScape?

Outputs:
- [ ] Possible options for achieving the above - e.g. describe the process that could work, with pros/cons
- [x] Test cases to try to check our assumptions
- [ ] Update https://github.com/sanger/lighthouse/issues/795 with the findings.

Timebox 2 days

**Comment by sdjmchattie** [comment]
When using the "Cherrypick" request type for Tecan cherrypicking (i.e. selecting Cherrypick as the Template while creating a new submission), the list of available Output Plate Purposes in the Plate Layout screen includes a number of plate purposes, but one of them is LB Cherrypick which is a generic plate purpose for plates that have been cherrypicked onto.  In order to test that this plate purpose will be suitable, the following was done:

- Create a few LSW-96 Stock plates and start a new submission with them using the Cherrypick request type.
- Complete the process, generating LB Cherrypick plates as destinations.
- Start another new submission with the Cherrypick request type, using a LB Cherrypick plate that was just created and another LSW-96 Stock plate.
  - The system generates a red warning that some of the samples (from the LB Cherrypick plate) already exist in a similar request and warning that you might not want to do that.  The warning can be ignored if the pick is intentional.
  - The process completes as usual an creates more destination plates.  See https://uat.sequencescape.psd.sanger.ac.uk/batches/70564
- Attempt to perform bed verification on the plates in the second iteration of cherrypicking in the batch shown above.
  - Go to https://uat.sequencescape.psd.sanger.ac.uk/robot_verifications and insert a user swipecard number, the worksheet barcode and the destination plate barcode.  The robot barcode must also be entered and is tricky to obtain if you don't have the robot in front of you.  Instructions to do so are [on confluence](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Robots).
  - The second step asks you to scan in the barcodes of the beds the plates are being placed on.  These can be generated using the same Confluence page information if just testing, otherwise they would be on the machine.
  - Once all the plates are in the correct beds according to the table, the verify button will take you to the download page for the Tecan machine's driver file.

So it has been demonstrated that the LB Cherrypick plate purpose will work even for second/third/fourth cherrypicking attempts.  The bed verification is also working.
