### ISSUE TITLE
DPL-906 As a TL (Tom) I would like to mockup a Sample Tracking report for SGE-Mave so that we can confirm the best format/columns with end users.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#342]
**Description**
As a TL (Tom) I would like to mockup a Sample Tracking report for SGE-Mave so that we can confirm the best format & columns with end users.

**Who the primary contacts are for this work**
LH

**Knowledge or Stake holders**
TW KT AY

**Additional context or information**
Create a Google Doc mocked up report with the columns and example data we can provide from MLWH.
Share with LH and walk through how it would be used in conjunction with the SSR WIP report.
Collect changes and future improvements.

**Comment by javidahmed64592** [comment]
[This table](https://github.com/sanger/unified_warehouse/blob/40a2666aad803b5b2180c27f1e3d8cb3cb2acd79/db/migrate/20170717092510_add_oseq_flowcell_table.rb#L16) says that `pipeline_id_lims` is the library type in Sequencescape named for compatibility with the `iseq_flowcell` table. Looking in that table, I found that library type does not seem to be 1:1 with sample because rows with different `id_sample_tmp` can have the same `pipeline_id_lims` (confirm this is correct?)

<img width="456" alt="image" src="https://github.com/sanger/General-Backlog-Items/assets/57677851/13a3dd3d-12a2-4d32-8c6f-d9f2ad5e2f81">
