### ISSUE TITLE
DPL-943 As a TL (Tom) I would like a data flow diagram of the Sample Tracking POC produced so that we can plan the implementation.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#345]
**Description**
As a TL (Tom) I would like a data flow diagram of the Sample Tracking POC produced so that we can plan the implementation.

**Who the primary contacts are for this work**
TW KT AY

**Knowledge or Stake holders**
LH

**Additional context or information**

  - Identify studies received in last 6 months -  (limit to just SGE/Mave for production, but nice to be able to expand this easily to test for other studies)
  - Find plates submitted in above studies
  - Extract data from mlwh_event associated with each column or set of columns
  - Extract data from flowcell tables associated with NPG sequencing run
  - Combine the different data artefacts into the report.

In doing so: 
  - Identify any common patterns or queries
  - Propose any interim data sets that are themselves generally useful.

The output should be:
*  a data flow diagram for the workflow to construct the Mocked Up report in #342 
*  a set of user stories / tasks to implement the above data flow. e.g. one arge SQL program using temp or intermediate tables or use external application (Janitor) as orchestrator / cron job.... etc...

Implementation questions to answer:
- What does the application consist of?
- Where does the code live?
- Where is it documented?
- How updates are tested to ensure correctness?
- [Nice to have] Do we need smoke tests? And if so where could they live and how would they be monitored?

**Comment by javidahmed64592** [comment]
I have created the following diagrams for outlining the data flow for the two queries used to populate the mocked up report:

1) https://lucid.app/lucidchart/c46d813b-f54c-48c6-a0e0-47eadaa26f1c/edit?viewport_loc=-243%2C-70%2C2999%2C1449%2C0_0&invitationId=inv_b5d0876b-af63-4f70-8e79-6a0b7b57af50

2) https://lucid.app/lucidchart/994f9e42-18f6-4066-9ccb-9f79c2b9ac12/edit?viewport_loc=590%2C272%2C1937%2C936%2C0_0&invitationId=inv_4d077428-0601-4475-a2c2-d2759184d381

**Comment by javidahmed64592** [comment]
I have updated the [Sample Tracking Data Flow (events)](https://lucid.app/lucidchart/994f9e42-18f6-4066-9ccb-9f79c2b9ac12/edit?viewport_loc=-56%2C-32%2C2384%2C1199%2C0_0&invitationId=inv_4d077428-0601-4475-a2c2-d2759184d381) diagram to show the table joins more explicitly, show how the fields can be used to filter for samples, studies etc.

I have also added a proposal for two temporary tables to be created which can simplify the query used to create the mock up report. I've added example SQL queries which can be used by an application such as `janitor` to populate these tables, and an example query to show these temporary tables being used to generate the report columns.

I still need to finish updating the equivalent diagram for the flowcell runs, and that will help refine these queries.

**Comment by yoldas** [comment]
flowcell diagram,
- The query (bottom left) could be written with CTE blocks to increase readability and to match the flow diagram.
- Sample flowcell run box (top middle), I want to point out that number of flowcells increases the number of rows in the result. Applying grouping early in a CTE will make the intention clear.

**Comment by javidahmed64592** [comment]
Regarding my proposed `role_events` table:

Q1. Creating a view should be possible and allow for the database to be queried in the same way as using a `WITH` statement with the benefit of not having to repeat the block of code across multiple SQL queries. We also would not need to update any table schemas if we wanted to add/remove fields from this view depending on what is useful. This leads to the question of, **where should the SQL query for creating this view live**? I assume it only needs to be run when we want to create or update the view, and not need to run it when new rows are added to the other tables.

I checked how long the query in the (currently) `WITH` statement takes using a date condition `(date >= 2023-09-01)` and it varies between 20-30 seconds. Presumably querying the view will be quicker than that.

Q2. If the tables were to be real tables, we could periodically update them using `janitor`. We would need to create the table schema and add a new task to `janitor` which checks for updates and writes them to the new table, similar to the `labware_location` task. That being said, it may be more efficient to create it as a view instead, as having it as a real table may not be any more useful than just having it as a view since we would only currently use it for the session.

I personally like the idea of creating it as a view, and we could potentially do the same for my proposed `role_subjects` table.

@TWJW-SANGER @KatyTaylor @stevieing
Any thoughts?

**Comment by javidahmed64592** [comment]
I have added links to the diagrams on the following Confluence page: https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Sample+Tracking+Proof+Of+Concept
