### ISSUE TITLE
DPL-1009 As a team (PSD) we would like to have a searchable, editable, shareable (with users) and clear structure for Pipeline, Project and Application documentation so that we can easily find information.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#352]
**Description**
As a team (PSD) we would like to have a searchable, editable, shareable (with users) and clear structure for Pipeline, Project and Application documentation so that we can easily find information.

**Who the primary contacts are for this work**
PSD Team

**Additional context or information**
Review existing Confluence documentation on PSD-Public under Pipeline, Project and Application.

Outputs:
- One starting location for documentation.
- A folder structure for Pipeline, Project and Application documentation
- A definition on what information goes (or doesn't go) in each area
- Guidance on anything that should be put elsewhere (github)

Note this work is **not** to actually move the documentation anywhere yet....
It is to come up with a structure and guidance on where documentation should be.

Timebox to 1.5 days

The outputs above should be reviewed by the team members.

Once consensus on the location and structure is achieved, we can start to refactor the existing documentation.

**Comment by KatyTaylor** [comment]
Hi @StephenHulme , looks good thank you. A couple of comments below.

- I've never noticed the Feedback Wall before! I think it would be better if it was flipped, so that the most recent comments are at the top.
- I'm not quite sure what your recommendations are exactly regarding the 'Repository docs Folder'. I think if it contains user-level documentation, that should go in the public Confluence space. When you say 'Recommended for specific use cases only', what use cases are you thinking of?
- I think there is an argument for having some developer-focused documentation in Confluence - for instance, what if you want to display a LucidChart diagram? It seems like our technical documentation could be a bit spread all over the place though, could be a problem finding what you're after.
- What's next? A story to do some migration of documentation & creation of placeholders?

**Comment by KatyTaylor** [comment]
Great thanks.
