### ISSUE TITLE
DPL-1084 As an RVI SSR I would like to be able to see how many times samples in a source plate have been cherry picked from so that we can judge if any volume is left for further sequencing in the source plates.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#369]
**User story**
As an RVI SSR I would like to be able to see how many times samples in a source plate have been cherry picked from so that we can judge if any volume is left for further sequencing in the source plates.

**Who are the primary contacts for this story**
Anna G
Scott T
Adrianne L
Lesley S
Sara S
Adam M

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Given a set of sample supplier_name ids we would like to generate a table showing for each cherry picking event on each sample in the list the sample supplier_name, Source Plate Barcode, Source Location and Dest Plate Purpose. An example is given below.
- [ ] The table data can be opened in Excel/Google sheets for further processing

| supplier name | source plate barcode | source location | destination plate purpose |
|---------------|-----------------------|----------------|---------------------------|
| SAMPLE_P1 | SQPP-46333-Q | A1 | RVI RT |
| SAMPLE_P1 | SQPP-46333-Q | A1 | RVI RT |
| SAMPLE_P2 | SQPP-46333-Q | A2 | RVI RT |

NB The source plate may or may not be a stock plate...

**Additional context**
Knowing the destination plate purpose for a cherry pick will allow the end users to estimate how much volume was taken from the source plate.
The remaining fields allow the end users to estimate the total volume taken from a given source plate & location.

The RVI cherry picking step does not appear to create any events in the MLWH_events database. (Unlike say the Heron Beckman and Biosero cherrypicking).

**Comment by KatyTaylor** [comment]
Hi @StephenHulme, I think your query is basically correct, apart from one issue:
- I think the joins to the `barcodes` table are incorrect - you're assuming the `asset_id` on `barcodes` links to `receptacles`, but it actually links to `labware`

Then, there are a few things I would suggest to make it more readable / make more sense to me. Pasting an ERD below to help:

![Screenshot 2024-03-07 at 14 20 44](https://github.com/sanger/General-Backlog-Items/assets/10407809/1fa71ef5-d78a-4826-b8a2-9365c7b2a479)

- I think it would be nicer if you queried first from requests, not receptacles. It's the one you're filtering on, it would make it nice and symmetrical, and avoid a couple of issues that it has currently.
- Some of your joins have the potential to return multiple rows, but you are treating it as if it will only return one. For instance, the joins to aliquots and barcodes. I think MySQL deals with this and just retrieves the first value of the list when you reference it in the SELECT part, but it would be nicer to either leave a comment saying this is intentional, or use some aggregations.
- The join back to receptacles (source_receptacle) seems redundant, as that's what you queried in the first place (solved if you start with requests instead).
- Would be nicer to use the study on the request (although would need to check the data is there).
- You join to aliquot first, using the receptacle id, and then to receptacle later. Would be more readable if you follow the order of the relationship - join request to receptacle, then to aliquot.
- No point in SELECTing requests.state if you're filtering on one value - but I assume you did it because you may want to change this filter
- Do you want to add a filter on a given list of sample supplier names in there?


V happy to talk anything through if it doesn't make sense.

**Comment by sdjmchattie** [comment]
> Potential SQL query solution:

@StephenHulme I'll let Katy's response above be the definitive answer on the database structure.  The only other suggestion I have is to consider using `AS` for the `INNER JOIN` lines to be consistent with the way you rename the `SELECT`ed columns at the top.  I prefer to add the word because it can be confusing to see a table name and then another non-table name immediately after just a space, even if the syntax is valid.

Also 100% personal preference, but you don't need to specify `INNER` as it's the default.  But I realise it does help people who are less familiar with the defaults so happy if you don't want to remove those.  I think Katy made a point about the plurality of some of the relationships.  I believe if there are multiple matches, you'll just get multiple rows in the response unless you do aggregations.

As this is quite a complicated query, would it be worth wrapping it in a view?  That way we create an interface for the SSR so that if the schema changes in some subtle way that breaks this query, they don't need to know as we should be maintaining the view to match the new schema.  It has drawbacks as well as upsides, but I don't like handing people SQL as complicated as this if they don't need to see it.  If you do create a view, bear in mind that the user of the view cannot override your `WHERE` clauses or something the `ORDER BY`s the rows, so it's often best to leave that in their hands except where you definitely want to reduce their visibility of entries.

**Comment by sdjmchattie** [comment]
LGTM.  This is purely from a readability perspective.  I can't comment on the structure of the query.  It should have a `;` on the end though to avoid unexpected behaviour if this gets used in a longer script.

**Comment by KatyTaylor** [comment]
Yes, it's really nice and readable, thanks.

A few comments:

**Multiplicity**
1. The join with barcodes could return multiple rows for a single labware. I notice you're filtering on barcode format with id 42 - what's the reason for this? Is this to try to avoid the multiplicity issue? If so, it's still possible (I think) to have multiple barcodes with the same format. I would personally aggregate the barcodes to take care of it.
Add a group by:
`GROUP BY requests.id`
and then in the `SELECT` part, add:
`GROUP_CONCAT(source_barcode.barcode)`
and
`GROUP_CONCAT(target_barcode.barcode)`

2. The join with aliquots could also return multiple rows for a single source receptacle, although I think it's unlikely to. I suppose if it does though, we do want to return all rows for it, because we want to find all samples that have been cherrypicked, not constrain it to one per well. So I think you can leave it as is. I would personally add a comment on the aliquots join line something like `-- It is possible to have multiple aliquots per well. If there are, we want to return them all.`

**Inner / left join**

What's the reason for the `LEFT JOIN` with aliquots? I think it could be an `INNER JOIN`. Because you're filtering based on a sample metadata value, if there are receptacles with no aliquots, they'll get filtered out here anyway. We're only interested in rows where the source receptacle has an aliquot (and what's the point of a cherrypick where there's nothing in the source well, anyway?).

**Filtering**

Where does the requirement to filter based on Study come from?
I think the thing to do is to filter on request_type = 'Cherrypick', if we're only interested in cherrypicks as the story suggests.

I think the filtering by study is the reason your results from training aren't bringing back cherrypicks - they're bringing back deep well stamping. Look at the 'requests' section on one of your source plates - https://training.sequencescape.psd.sanger.ac.uk/labware/27505561#requests-table-container - no cherrypick requests, just deep well stamping requests.

**Comment by KatyTaylor** [comment]
@StephenHulme Looks good to me! I sanity checked the first line of data too and it makes more sense this time.

**Comment by TWJW-SANGER** [comment]
Just catching up and just in case you haven't already noticed the default separator for GROUP_CONCAT is a comma...

It can sometimes cause issues with csv exports. In the past I have resorted to semi-colons.
