### ISSUE TITLE
BUG - Warehouse & logging issues

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/General-Backlog-Items#38]
**Describe the bug**
Timeline of events / issues noticed today (02/09/2020)
1. We did an Events Warehouse deployment yesterday afternoon
2. Noticed this morning our new events were not getting sent to WH
3. Noticed Kibana had been down since 4am this morning
4. Noticed a puma service (Events WH API) was running that shouldn't be
5. Stopped above service
6. Deleted some logs in ware-prod to clear up space (syslog and .gz syslog files)
7. At some point around then, RabbitMQ stoped letting us in ("Management API returned status code 500")
9. Neil noticed "a sample’s metadata wasn’t updating in mlwh"

**Comment by KatyTaylor** [comment]
James / Eduardo are backing up and then deleting var/log/syslog.1 (2.6GB) to clear space on ware-prod

**Comment by JamesGlover** [comment]
Root cause of the massive logs was the unintended activation of the puma server for the event warehouse, which constantly failed to spawn and spat out tonnes of logs. These caused the syslog to increase to an enormous size, and filleld the disk.
Fixes:
1) Stop the puma server spawning, or fix the problem that was causing it to fail
2) Establish proper log size limits to prevent future disasters having a similar effect.

Wrt. Step 2. I couldn't track down what was managing the current log rotation, although could se evidence of a daily task. Suspect its either part of systemd or rsyslog but couldn't track it down. There are guides online for configuring rsyslog for better log rotation, and similarly systemd is supposed to have some inbuilt control of this as well. However my understanding of how the systems all inter-relate isn't great.
