### ISSUE TITLE
Y24-159 - Update create-labware schema to add retention instructions

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/General-Backlog-Items#412]
**User story**
As developers, we need to add a `retention_instruction` field into the [`create-labware`](https://redpanda.training.psd.sanger.ac.uk/console/schema-registry/subjects/create-labware?version=latest) schema. This is to facilitate specifying retention instructions in the warehouse for each tube/plate submitted. The resulting schema should be published as a new version in [RedPanda](https://redpanda.training.psd.sanger.ac.uk/console/schema-registry).

**Who are the primary contacts for this story**
Steve / Stuart / Dasun

**Who is the nominated tester for UAT**

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] All messages received on the current message schema version are treated as implicitly specifying "Return to customer after 2 years" for the retention field.
- [ ] ~All messages received on the new message schema version must contain `retention_instruction` field.~ If the message does _not_ contain a retention instruction field (check https://github.com/sanger/General-Backlog-Items/issues/412#issuecomment-2186485766), a default value must be used.  
- [ ] The new version is published and stakeholders are made aware of it. The default value for the retention instruction needs to be properly communcated with the clients as this is defining how long SciOps can legally hold the samples and whether they are destroyed or returned. 
- [ ] The `retention_instruction` is properly documented in the schema using the [`doc`](https://avro.apache.org/docs/1.11.1/specification/#messages) attribute.

References
This story has a non-blocking relationship with:
- https://github.com/sanger/tol-lab-share/issues/85

**Additional context**

**Comment by dasunpubudumal** [comment]
Our [RedPanda](https://redpanda.uat.psd.sanger.ac.uk/console/schema-registry) schemas uses [default compatibility](https://docs.redpanda.com/23.2/manage/schema-registry/#configure-schema-compatibility), which makes it **not possible** to add required fields. It allows deleting existing fields and/or adding optional fields.

This needs to be addressed before proceeding with the story. If the field is made optional, it will be required to have an implicit default value. Or else, we will have add some additional custom validation logic in `tol-lab-share` to validate the new filed.

**Comment by stevieing** [comment]
Schema changes made on schema registry for UAT.

**Comment by sdjmchattie** [comment]
Just pasting the current change here for others to see:

```
{
    "name": "retentionInstruction",
    "type": {
        "type": "enum",
        "name": "allowedRetentionInstruction",
        "symbols": [
            "destroy_after_2_years",
            "return_to_customer_after_2_years",
            "long_term_storage"
        ],
        "default": "destroy_after_2_years"
    },
    "doc": "The retention instruction (what the customer wants to happen to the sample)"
}
```

Parsing out what this means, it's an optional field called `retentionInstruction` and it has an enum with three values.  One of the values is defined as a default  in the type definition.

Questions I have @stevieing :

- Should the default value be defined alongside the `name` and `doc` rather than inside the `type`?
- Is the default value correct?  I read above in this issue that it is to return to customer after 2 years.
- Less of a question and more of an observation -- so written this way, I _think_ the publisher must either provide one of the enum values or leave the field completely out of the message.  I don't know what happens when they try to assign it with a `null`/`None`/`nil` value.  The schema doesn't allow `null` as a type.  Perhaps that's ideal and I haven't tested what happens to the encoded message under these conditions.

**Comment by sdjmchattie** [comment]
So I did some tests.

- Having `"default"` defined at the level it is means you cannot leave this field unspecified so it does need to move out one level.
- Not making `null` one of the types means exactly as I said above.  You can leave the field out entirely.  You can include the field as long as you give it one of the enum values.  If you put the field in but assign it `null`, the validation fails on the message.  Perhaps we want it that way.  If not, we need to put `null` in as a type in a union.

**Comment by sdjmchattie** [comment]
I decided to try to understand what it means to have "default" in the enum itself instead of at the root of the field.  It's a safety mechanism for enums specifically and only gets used when decoding a message, not during encoding.  If you (somehow) received a message that gives a value for the field that isn't in the enum list, the default would be decoded instead.  It's unclear how a message would be badly encoded to start with, but it could possibly happen if you are decoding with the wrong schema version, or the publisher wrote the message without using a valid Avro library.

**Comment by stevieing** [comment]
Thanks @sdjmchattie. I will make those changes.

**Comment by stevieing** [comment]
> So I did some tests.
> 
>     * Having `"default"` defined at the level it is means you cannot leave this field unspecified so it does need to move out one level.
> 
>     * Not making `null` one of the types means exactly as I said above.  You can leave the field out entirely.  You can include the field as long as you give it one of the enum values.  If you put the field in but assign it `null`, the validation fails on the message.  Perhaps we want it that way.  If not, we need to put `null` in as a type in a union.

Not sure exactly what you are saying here. If I move the default up to the same level as doc is that suffiicient. Or is it better to create it as a union type?

**Comment by sdjmchattie** [comment]
Yes what you're showing here is what I would expect.  This offers:

* Publisher left the `retentionInstruction` field out of the message: The message is encoded with `return_to_customer_after_2_years` for that field.
* Publisher included the field with a `null` value: The message fails validation because you can't specify `null` for this field.
* Publisher included the field and gave a valid enum value: The message is encoded with the value they gave.

To answer your question, to make a union, you change the root level `"type"` to an array instead of an object.  For example:

```
{
    "name": "retentionInstruction",
    "type": [
        "null",
        {
            "type": "enum",
            "name": "allowedRetentionInstruction",
            "symbols": [
                "destroy_after_2_years",
                "return_to_customer_after_2_years",
                "long_term_storage"
            ]
        }
    ],
    "default": null,
    "doc": "The retention instruction (what the customer wants to happen to the sample)"
}
```

What this does is allows the field to be specified as either one of the enum values or as `null`.  If you wanted the default to be one of the enum values, you'd have to switch the two types around in the array because the first type in the array must match the type of the default.
