### ISSUE TITLE
Y24-244 - Bump GitHub workflow dependency checkout from v2 to v4

### ISSUE THREAD

**Issue by SHIV5T3R** [sanger/General-Backlog-Items#433]
**Describe the Housekeeping**
Across our repositories, we use an action called checkout. For most repos, this is currently running on v2 and v3 which is (somewhat) deprecated. Bumping this to v4 can avoid problems with actions if v2 ever becomes completely unusable.

**Comment by KatyTaylor** [comment]
Pulled this out of the main description:

**Additional context**
In addition to this, we can also use shared workflows for our actions so that we can easily manage them, similar to the issuer and tech debt actions. This consolidation can help us to keep our actions consistent for the future.

We agreed yesterday to make new stories for this part.
