### ISSUE TITLE
Y24-355 - As a team we would like to minimise the dependencies of Monit.d so that it is less likely to be impacted by service outages. 

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#454]
**User story**
As a team we would like to minimise the dependencies of Monit.d so that it is less likely to be impacted by service outages. 

**Who are the primary contacts for this story**
TW, PSD

**Who is the nominated tester for UAT**
This is to be tested by the PSD team

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Remove the MySQL dependency of Monit.d
- [ ] Identify and where possible remove any other service dependencies other than the OpenStack instance it is running on.

**Additional context**
When the MySQL databases were being taken offline to be patched we think we discovered that Monit has a dependency on a MySQL database provided by the DBA team.
_Ideally_ our monitoring solution would have no dependencies in common with the applications being monitored - otherwise we risk an outage on one of those services impacting the applications AND the system that alerts us to problems.
In practice, Monit will need to depend on OpenStack, its instances, images and networking (which are monitored by other teams and have a large impact if they go down beyond just PSD).

**Comment by BenTopping** [comment]
We purposefully moved off sqlite during the [`eta -> theta openstack` migration ](https://github.com/sanger/General-Backlog-Items/issues/58) because of concerns with sqlite backups and scaleability.

I think there are a couple options:
- Move back to sqlite (figure out if we can migrate from mysql back to sqlite)
  - Monit db info is controlled in the packer project in the mmonit server.xml.j2 file
- Move to an isolated MySQL instance - e.g. run mysql directly on the instance instead of through the DBAs.
- Identify if we can move DBA MySQL instance to a separate instance that is updated at a different time to all other MySQL upgrades.

**Comment by BenTopping** [comment]
### Team meeting 15/11/24

Two separate use cases for M/Monit:
1. Monitoring
  - The monitoring solution should not be coupled to any services that the apps being monitored are also coupled to. In this case MySQL.
  - 
2. Shutdown startup process
  - M/Monit is not the only way to control shutdown and start up of instances but it is a useful tool.
  - M/Monit is the current main method for PSD so it would be beneficial to not have it coupled to the same dependencies as the apps being shutdown.


Team agreed the preferred solution is to have a self hosted MySQL instance.
1. We don't need to worry too much about updates / management because it is an isolated instance so not a security concern.
2. Current production MySQL db is 56MB so easy to backup and dump.
3. Benefits of a more performant / scaleable db compared to sqlite and easier to transfer existing data across.
4. Useful because it completely removes any dependenices of M/Monit.


Next steps:

- [ ] Review the value of the existing M/Monit data.
- [ ] Review how we can transfer the existing data across (or start from scratch).
- [ ] Identify how we can deploy M/Monit with a mysql db setup.
- [ ] Consider new values for permanent data storage (currently 3 year removal cycle for stats and events are never removed)
- [ ] Create a new implementation story based on the results above.

**Comment by BenTopping** [comment]
Follow up story: https://github.com/sanger/packer/issues/28
