### ISSUE TITLE
GPL-689 As a team we need to better understand the LIMS work involved to implement the Beckman

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#59]
**Description**
As a team we need to better understand the LIMS work involved to implement the Beckman

**Who the primary contacts are for this work**
Scott / Lesley

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is Andrew

**Additional context or information**
Meeting arranged for 12/10.
Expected outcomes:
- sequence flow diagram (WIP) https://app.lucidchart.com/lucidchart/40f7879f-57b8-494f-a1ad-e2828800c375/edit?shared=true&page=0_0#?folder_id=home&browser=icon
- list of new features required
- list of features where LIMS automation is required

**Comment by andrewsparkes** [comment]
Meeting with Scott and Beckman at 1.15 13/10/20 to discuss robot process flow (scheduling and workflow). Questions about destination plates and what happens when full, or when current source would fill destination 1 and overflow into destination 2. Ideally users want to move that completed destination off to the next pipeline step.

NB. Expecting delivery of all 4 robots mid-November (16th?) with each being SAT tested once commissioned.
