### ISSUE TITLE
GPL-718 Update PAM report querys to reflect changes in design

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#81]
**User story**
Update example queries and communicate to PAM.

**Who are the primary contacts for this story**
PAM
Ian W (Principal contact)
Cristina A
Lee W

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Update query for Beckman cherrypicking event
- [x] Update query for adoption of filtered positive fields (rather than duplication of current fit-to-pick rules)
- [ ] Resolve this - https://rt.sanger.ac.uk/SelfService/Display.html?id=710023 - if poss

Pages to update:
- [x] https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Warehouse+queries+for+sample+tracking
- [x] https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/h.+Progression+reporting
- [x] https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=111057201

Other tasks:
- [x] add comment summarising nature of above changes

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/crawler/issues/167

**Additional context**
Should become easier to select filtered positives, and hopefully easier to identify what has been cherrypicked and what hasn't.

**Comment by KatyTaylor** [comment]
Some of the relevant queries are here - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Warehouse+query+for+sample+tracking

More are here - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/h.+Progression+reporting

**Comment by TWJW-SANGER** [comment]
Also query on finding cherry picked samples sent offsite will need checking / changing: https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=111057201

**Comment by KatyTaylor** [comment]
Have updated queries on the following pages:
https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Cherrypicking+Events
https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/h.+Progression+reporting
https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=111057201

The main things that caused changes to be needed were:
- Cherrypicking events - 'robot_verified' event is not fired for Beckman-picked samples - use 'lh_beckman_cp_destination_created' instead
- 'Friendly name' - Events for Beckman-picked samples have different format values in the 'friendly_name' field on the 'subjects' table - join using the uuid instead (have to fiddle around with converting between binary and hex strings)
- Sample name - Beckman-picked samples have different format values in the 'name' field in the 'sample' table - join to Events WH using the uuid instead, or use the 'sanger_sample_id' field if the query uses `LIKE 'Heron%'`

I can't do the task 'Update query for adoption of filtered positive fields (rather than duplication of current fit-to-pick rules)' yet, as not all samples have these fields filled out yet (prod migration currently being applied over the next few days).

**Comment by KatyTaylor** [comment]
Update:

Putting this back in 'to do' to pick up a higher priority story.
Spent quite a lot of yesterday thinking about the 'samples sent off site query' - https://rt.sanger.ac.uk/SelfService/Display.html?id=710023

Main issues seem to be:
- The existing query on https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=111057201 only returns around 14,232 rows (on 26th Jan), whereas Cristina's manually created list has around 23,775 rows (from spreadsheet sent by Ian on 27th Jan). Two possible differences for the gap are:
    - The query uses the 'labware.received' event, which only fires if the Sequencescape Reception page is used. If the labware is scanned directly into LabWhere, this event is not fired.
    - The query joins to the 'sample' table, which will miss any samples that have not gone into Sequencescape (ones that were sent off site in their original plates).

Trying to come up with a better query, these are the obstacles I hit:
- Better LabWhere events to use would be those fired by LabWhere itself (e.g. 'labwhere_create', 'labwhere_update', and the others), however, these events do not have sample information attached to them, only the plate barcode.
- Working back from the plate barcode to the actual samples it contains cannot be done (?) using the warehouses, the only way is to look directly in the Sequencescape database.
- Unless the plate is a lighthouse plate, in which case you can find the samples by joining to the lighthouse_sample table - however, I had performance issues trying to do this (tried to solve by adding an index on plate_barcode but didn't seem to make a difference).
